// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYkFhpvXlyAh0V5rYxGO7XMti6EdfxQhM',
    appId: '1:113466658501:web:7c8bf53e18758c7318aaac',
    messagingSenderId: '113466658501',
    projectId: 'proyecto1-98a31',
    authDomain: 'proyecto1-98a31.firebaseapp.com',
    storageBucket: 'proyecto1-98a31.firebasestorage.app',
    measurementId: 'G-PYN2GSL73S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwOV19fj_fIe7mWLxU8ESSROE2eh4Ccfo',
    appId: '1:113466658501:android:2e23792e3c4c856e18aaac',
    messagingSenderId: '113466658501',
    projectId: 'proyecto1-98a31',
    storageBucket: 'proyecto1-98a31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVixHxS_Gkn5xmriEdIGujRpkKLK5Nt_8',
    appId: '1:113466658501:ios:f65be551bbbe07c718aaac',
    messagingSenderId: '113466658501',
    projectId: 'proyecto1-98a31',
    storageBucket: 'proyecto1-98a31.firebasestorage.app',
    iosBundleId: 'com.example.proyecto1',
  );
}
